### PR TITLE
Format docstrings for correct display in sphinx-generated bootstrap pages

### PR DESCRIPTION
**Pull request by santiagogaray**
Hi @chriswmackey,

I started with this library and I stumbled upon a couple of issues when generating the pages that I hope you can help me with:

1)  
Extension error:
Could not import extension sphinx_click.ext (exception: No module named click)
From the conf.py file I noticed the need of the sphinx-click extension so I installed it through pip:  pip install sphinx-click. 
At that point the message still comes up on the sphinx build command. I'm sure I'm missing a library or something. Any suggestions?

2)
When I disabled the sphinx-click extension to generate the pages that don't need it found this error:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\sphinx\ext\autodoc\importer.py", line 154, in import_module
    __import__(modname)
  File "C:\Users\sgara\Documents\GitHub\dragonfly-core\dragonfly\model.py", line 19, in <module>
    class Model(_BaseGeometry):
  File "C:\Users\sgara\Documents\GitHub\dragonfly-core\dragonfly\model.py", line 64, in Model
    UNITS = hb_model.UNITS
AttributeError: type object 'Model' has no attribute 'UNITS'
If I understand this right seems to be pointing to the honeybee.MODEL class. There is no UNITS property in it. Is this a bug?

### CODE REVIEW

**Comment by chriswmackey** [comment]
@santiagogaray ,
I will double-check on my end but I think both of these issues are the result of you not installing all of the dependencies of this repo to your machine. If you run [the commands under step 2. of the Readme](https://github.com/ladybug-tools/dragonfly-core#local-development), these issues should go away for you.

**Comment by chriswmackey** [comment]
Yep, the issues are definitely the result of you not installing the dev-requirements.txt. Once you do that, everything should run smoothly.

**Comment by santiagogaray** [comment]
Thanks @chriswmackey, you were right,  I apologise, I've completely overseen the dependencies.
Well the good news is that after generating all the pages everything look good so  what I pushed earlier in those commits still apply. 
Feel free to take a look and please let me know if you have any comments. I can work on the other dragonfly-energy library in the meantime.

**Comment by chriswmackey** [comment]
Glad to hear it. I'll review this code shortly, then.

**Pull request merged**
